### ISSUE TITLE
Trademark violation

### ISSUE THREAD

**Issue by jacobsalmela** [IcedComputer/Personal-Pi-Hole-configs#1]
Pi-hole® is a [registered trademark of Pi-hole LLC](https://pi-hole.net/trademark-rules-and-brand-guidelines/).  I request that you please change the name of your repository as soon as possible so as not to confuse it with the Pi-hole brand.

It looks like your just using it to host a hosts file, but nonetheless, it's an infringement on our trademark.

You can rename it to something like `hosts-for-pi-hole` or `myhosts-for-pi-hole` or something to that extent.  Please ping me when this is complete.  Thank you!

**Comment by IcedComputer** [comment]
Sorry about that - Updated.
